# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 119653695755a4205d98dfd468d56c11bce1f555d8a7e274f7a9473e5f91471395fda769b49fa602b3ebdc9d3b03d9424d0333bdeea2e625e20984b9e48c8226

test:
  secret_key_base: 2e2b1c876a094f06f0e476e8e32d0186c827d7c4eb67323ca0f6628bb0f2134fd328218396804b69b06290b35ad586eb831e83b53c68f24eeddc9ccc39876409

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
